id: P006826
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG17214
  title: བཅོ་བརྒྱད་ཁྲི་ཆེན་རིན་པོ་ཆེའི་མཛད་རྣམ་མདོར་བསྡུས།
  author: ''
  volumes:
    805865e366a94e419443f1b6284762e6:
      image_group_id: I1KG17642
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
